FROM node:16

ENV MONGODB_CONNECTION_PROTOCOL ...
ENV MONGODB_DB_NAME ...
ENV MONGODB_CLUSTER_ADDRESS ...
ENV MONGODB_USERNAME ...
ENV MONGODB_PASSWORD ...

WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .

CMD ["npm", "start"]